/** Preview art for a future Ninth Life collection. Not minted. Not pullable. */
export type MintPreview = {
  id: string;
  name: string;
  rarity: "rare" | "ultra";
  supply: string;
  src: string;
  diamondSrc?: string;
  copy: string;
  set: "pfp" | "scene";
};

export function ultraDiamondSrc(id: string): string | undefined {
  if (!id.startsWith("nft.pfp-")) return undefined;
  return `/machine/nfts/${id.slice(4)}-diamond.jpg`;
}

export const NINTH_LIFE_PREVIEWS: readonly MintPreview[] = [
  {
    id: "nft.ninth-life",
    name: "Ninth Life",
    rarity: "rare",
    supply: "limited",
    src: "/machine/nfts/ninth-life.jpg",
    copy: "Collection rare. Needs a 30-day $CATE hold. Not live.",
    set: "scene",
  },
  {
    id: "nft.pfp-crown",
    name: "Crown",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-crown.jpg",
    diamondSrc: "/machine/nfts/pfp-crown-diamond.jpg",
    copy: "Gold crown, fur collar. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-drip",
    name: "Drip",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-drip.jpg",
    diamondSrc: "/machine/nfts/pfp-drip-diamond.jpg",
    copy: "Cuban link and hoop. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-orbit",
    name: "Orbit",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-orbit.jpg",
    diamondSrc: "/machine/nfts/pfp-orbit-diamond.jpg",
    copy: "Gold helmet, visor open. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-tuxedo",
    name: "Tuxedo",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-tuxedo.jpg",
    diamondSrc: "/machine/nfts/pfp-tuxedo-diamond.jpg",
    copy: "Black velvet, gold bow. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-blade",
    name: "Blade",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-blade.jpg",
    diamondSrc: "/machine/nfts/pfp-blade-diamond.jpg",
    copy: "Mempo up, gold armor. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-ice",
    name: "Ice",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-ice.jpg",
    diamondSrc: "/machine/nfts/pfp-ice-diamond.jpg",
    copy: "Diamond choker and studs. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-pharaoh",
    name: "Pharaoh",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-pharaoh.jpg",
    diamondSrc: "/machine/nfts/pfp-pharaoh-diamond.jpg",
    copy: "Nemes and cobra crest. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-hoodie",
    name: "Hoodie",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-hoodie.jpg",
    diamondSrc: "/machine/nfts/pfp-hoodie-diamond.jpg",
    copy: "Black zip, gold pull. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-tophat",
    name: "Top Hat",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-tophat.jpg",
    diamondSrc: "/machine/nfts/pfp-tophat-diamond.jpg",
    copy: "Monocle and silk hat. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-viking",
    name: "Viking",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-viking.jpg",
    diamondSrc: "/machine/nfts/pfp-viking-diamond.jpg",
    copy: "Gold horns. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-dj",
    name: "DJ",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-dj.jpg",
    diamondSrc: "/machine/nfts/pfp-dj-diamond.jpg",
    copy: "Gold studio cans. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-cowboy",
    name: "Cowboy",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-cowboy.jpg",
    diamondSrc: "/machine/nfts/pfp-cowboy-diamond.jpg",
    copy: "Gold stetson. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-leather",
    name: "Leather",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-leather.jpg",
    diamondSrc: "/machine/nfts/pfp-leather-diamond.jpg",
    copy: "Biker jacket. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-halo",
    name: "Halo",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-halo.jpg",
    diamondSrc: "/machine/nfts/pfp-halo-diamond.jpg",
    copy: "Halo and gold feathers. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-beanie",
    name: "Beanie",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-beanie.jpg",
    diamondSrc: "/machine/nfts/pfp-beanie-diamond.jpg",
    copy: "Gold knit, ears out. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.pfp-lei",
    name: "Lei",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/pfp-lei.jpg",
    diamondSrc: "/machine/nfts/pfp-lei-diamond.jpg",
    copy: "Gold orchids. Ultra PFP.",
    set: "pfp",
  },
  {
    id: "nft.the-mark",
    name: "The Mark",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/the-mark.jpg",
    copy: "Face in the gold C.",
    set: "scene",
  },
  {
    id: "nft.the-yank",
    name: "The Yank",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/the-yank.jpg",
    copy: "Cate on the lever.",
    set: "scene",
  },
  {
    id: "nft.yarn-oracle",
    name: "Yarn Oracle",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/yarn-oracle.jpg",
    copy: "The yarn is the pull.",
    set: "scene",
  },
  {
    id: "nft.believe",
    name: "Believe",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/believe.jpg",
    copy: "Peak above the clouds.",
    set: "scene",
  },
  {
    id: "nft.the-capsule",
    name: "The Capsule",
    rarity: "ultra",
    supply: "1/1",
    src: "/machine/nfts/the-capsule.jpg",
    copy: "Prize still in the shell.",
    set: "scene",
  },
] as const;
